task:
  container:
    image: cirrusci/flutter:stable
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  activate_script: pub global activate flutter_plugin_tools
  matrix:
    - name: build_plugin_apk
      script:
        - yes | sdkmanager --licenses
        - cd example
        - flutter build apk