task:
  container:
    image: cirrusci/flutter:stable
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  activate_script: pub global activate flutter_plugin_tools
  matrix:
    - name: build_app_apk
      script:
        - cd example
        - flutter build apk

task:
  osx_instance:
    image: catalina-xcode-11.6-flutter
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  activate_script: pub global activate flutter_plugin_tools
  matrix:
    - name: build_app_ipa
      script:
        - cd example
        - flutter build ios --no-codesign