name: Docker Mac
on: 
  workflow_dispatch:
    branches:
    - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Docker
      run: |
        brew cask install docker-toolbox
        docker-machine create --driver "virtualbox" TestApp
        eval "$(docker-machine env TestApp)"
        docker-machine ls
        docker pull ibmcom/ibm-mobilefoundation-ce:latest
        
        CONTIANER_ID=$(docker run -d -p 9080:9080 -p 9443:9443 -e MFPF_ANALYTICS_PROTOCOL=http -e ANALYTICS_SVC_NAME=localhost -e ANALYTICS_PORT=9080 -e MFPF_SERVER_PROTOCOL=http -e ADMIN_HOST=localhost -e MFPF_SERVER_PORT=9080 -e RUNTIME_SVC_NAME=localhost -e MFPF_ANALYTICS_RECVR_HOST=localhost ibmcom/ibm-mobilefoundation-ce)
        docker ps
        echo "Container ID: ${CONTIANER_ID}"

        sleep 30

        echo "Getting the logs"
        docker logs ${CONTIANER_ID}