name: Docker Mac
on: 
  workflow_dispatch:
    branches:
    - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Docker
      run: |
        brew install homebrew/cask/brew-cask
        brew cask install docker
        docker pull ibmcom/ibm-mobilefoundation-ce:latest