name: Docker Test
on: 
  workflow_dispatch:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test install docker
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
        wget -qO - https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable" 
        sudo apt-get update
        apt-cache policy docker-ce
        sudo apt-get install -y docker-ce
        sudo systemctl status docker

        docker pull ibmcom/ibm-mobilefoundation-ce:latest

        CONTIANER_ID=$(docker run -d -p 9080:9080 -p 9443:9443 -e MFPF_ANALYTICS_PROTOCOL=http -e ANALYTICS_SVC_NAME=localhost -e ANALYTICS_PORT=9080 -e MFPF_SERVER_PROTOCOL=http -e ADMIN_HOST=localhost -e MFPF_SERVER_PORT=9080 -e RUNTIME_SVC_NAME=localhost -e MFPF_ANALYTICS_RECVR_HOST=localhost ibmcom/ibm-mobilefoundation-ce)
        docker ps
        echo "Container ID: ${CONTIANER_ID}"

        sleep 30

        echo "Getting the logs"
        docker logs ${CONTIANER_ID}

        curl http://127.0.0.1:9080/mfp/api/az/v1/token

    - name: Register app
      run: |
        cat <<EOF > ./registerconfig.json
        {
          "applicationKey":{
              "version":"1.0.0",
              "clientPlatform":"android",
              "packageName":"com.ibm.test"
          },
          "displayName":"example"
        }
        EOF
        curl -X POST "http://127.0.0.1:9080/mfpadmin/management-apis/2.0/runtimes/mfp/applications?async=false&locale=en_US" -H "Content-Type: application/json" --user "admin:admin" -H "cache-control: no-cache" -d @./registerconfig.json -o output.json
        cat ./output.json
