name: Docker Mac
on: 
  workflow_dispatch:
    branches:
    - master
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Docker
      run: |
        brew cask install docker-toolbox
        docker-machine create --driver "virtualbox" TestApp
        eval "$(docker-machine env TestApp)"
        docker pull ibmcom/ibm-mobilefoundation-ce:latest