name: Publish package to pub.dev
on: 
  workflow_dispatch:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
        channel: 'stable'
    - name: Set version as env variable
      run: |
        echo "VERSION=8.0.$(date +'%Y%m%d%H')" >> $GITHUB_ENV
    - name: Echo version number
      run: echo $NOW
    - name: Update version
      working-directory: ./
      run: |
        flutter pub global activate cider
        flutter pub global run cider:cider version $VERSION
    - name: Setup credentials
      working-directory: ./
      run: |
        mkdir -p ~/.pub-cache
        cat <<EOF > ~/.pub-cache/credentials.json
        {
          "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
          "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
          "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
          "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
          "expiration": 1570721159347
        }
        EOF
    - name: Publish package
      working-directory: ./
      run: pub publish -f
    - name: Update version
      working-directory: ./
      run: |
        if [[ -z $(git status -s) ]]
        then
          echo "No changes"
        else
          echo "Changes made, Commit needed"
          git config user.name ${{ secrets.GH_USER }}
          git config user.email "${{ secrets.GH_MAIL }}"
          git branch
          git add .
          git commit -m "Updating version to $VERSION"
          git push "https://${{ secrets.GH_TOKEN }}@github.com/rajarahul12/flutter_package.git" HEAD:master
        fi